language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: hemmalaget.se
  on:
    branch: master
