language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

before_install:
  - sudo add-apt-repository ppa:danmbox/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install -y pngquant

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
