language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

# greenkeeper-lockfile scripts
before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # package-lock.json was introduced in npm@5
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist
  fqdn: hemmalaget.se
  on:
    branch: master
